name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Rancher-Action-Example-Workflow
    runs-on: ubuntu-latest    
    steps:
      - name: Rancher CLI Action
        uses: colbyhill21/Rancher-Action@master
        with:
          args: '"get pods"'
          token: ${{ secrets.RANCHER_TOKEN }}
          context: ${{ secrets.RANCHER_CONTEXT }}
          url: ${{ secrets.RANCHER_URL }}
